---
# Só mude aqui!!!!
author: "Lucas Reis Oliveira de Andrade"
title: "1° Relatório: Descrição do Experimento da Catapulta."
bibliography: referencias.bib
# A partir daqui nao faca alteracoes!!!!!
link-citations: true
csl: associacao-brasileira-de-normas-tecnicas-ipea.csl
subtitle: "<a href='https://bendeivide.github.io/courses/epaec/' target='_blank'>Estatística e Probabilidade</a> </br> <a href='https://bendeivide.github.io' target='_blank'>Prof. Ben Dêivide (DEFIM/CAP/UFSJ)</a>"
include-before-body: header.html
date: now
date-format: "DD/MM/YYYY, HH:mm"
lang: pt-BR
format:
  html:
    toc: true
    number-sections: true
    theme: bootstrap
    #css: styles.css
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: false
  message: false
---


## Introdução

Usaremos o experimento da catapulta para estudarmos os conceitos da disciplina de estatística e probabilidade de forma prática durante todo semestre. O experimento foi proposto como uma atividade didática com o objetivo de simular a coleta e análise de dados reais, possibilitando a aplicação de técnicas estatísticas descritivas. A partir da realização de múltiplos lançamentos de uma bolinha.


## Objetivos

### Objetivo geral

O objetivo geral: Usando a catapulta para atirar uma bolinha, entender como funciona a coleta, organização e apresentação de dados.

### Objetivos específicos

O primeiro passo do experimento consistiu em coletar dados experimentais dos lançamentos da catapulta, medindo a distância de cada lançamento.Após concluirmos a coleta dos dados brutos, organizamos todos dados em uma planilha. E posteriormente, usando o software Rstudio, construimos uma tabela de frequências.

---

## Fundamentação Teórica

A estatística descritiva tem como finalidade organizar, resumir e descrever um conjunto de dados. Entre os principais conceitos utilizados neste experimento, destacam-se: 

Dados brutos: Valores coletados diretamente do experimento, sem qualquer organização prévia. Dados em Rol: Conjunto de dados ordenados em ordem crescente ou decrescente.
Frequência absoluta (Fi): Número de vezes que um determinado valor ou classe ocorre.
Frequência relativa (Fr): Proporção da frequência absoluta em relação ao total de observações.
Frequência acumulada (abaixo de): Soma das frequências até aquela classe (incluindo ela).
Frequência acumulada (acima de): Soma das frequências daquela classe até o final.
Frequência acumulada percentual (abaixo de): Porcentagem acumulada até aquela classe.
Frequência acumulada percentual (acima de): Porcentagem acumulada daquela classe até o final.
Média aritimética: Medida de tendência central que representa o valor médio do conjunto de dados.

Abaixo algumas fórmulas importantes para a tabulação dos dados.

Fórmula para a média aritimética.

A média representa o valor central de um conjunto de dados. Ela é obtida somando todas as observações e dividindo pelo número total de elementos. No experimentos da catapulta, a média indica a distância média dos lançamentos.
$$
\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i
$$
Fórmula para a frequência relativa.
Representa a proporção de ocorrência de um valor ou classe em relação ao total de dados.
$$
f_r = \frac{f_i}{n}
$$
Fórmula para a frequência percentual.
Frequência relativa expressa em porcentagem.
$$
f_{\%} = \frac{f_i}{n} \times 100
$$
Fórmula para o ponto médio da classe.
O ponto médio representa o valor central de um intervalo de classe em dados agrupados.
$$
x_m = \frac{L_i + L_s}{2}
$$
---

## Metodologia

Materiais utilizados: 1 Catapulta de mesa. 1 Bolinha de "ping-pong", usada nos lançamentos. 1 Trena, usada para a medição da distância de cada arremesso.

Procedimento: Para minimizar variações sistemáticas, um único integrante do grupo foi responsável por realizar todos os lançamentos da catapulta. A medição das distâncias foi realizada por dois integrantes, enquanto outros dois ficaram responsáveis pelo registro e organização dos dados. Ao todo, o experimento teve um total de 40 arremessos executados.

---

## Análise de Dados

Os dados coletados a partir dos 40 lançamentos da catapulta foram organizados e analisados com o auxílio do software R. Inicialmente, os valores foram ordenados em rol, permitindo uma melhor visualização da distribuição das distâncias obtidas.

Observa-se que a maior parte dos valores encontra-se concentrada entre aproximadamente 1,60 m e 2,05 m, indicando uma tendência de agrupamento dos dados em torno desse intervalo.

A análise da tabela mostra que a classe de maior frequência é o intervalo de 1,67 m a 1,99 m, contendo 27 observações. Isso indica que a maior parte dos lançamentos se concentrou nessa faixa de distância.

Por outro lado, observa-se a presença de valores mais elevados, especialmente nas classes finais. Esses valores possuem baixa frequência e podem ser caracterizados como possíveis outliers, pois se distanciam significativamente do padrão observado na maior parte dos dados.

De modo geral, os resultados indicam baixa variabilidade, com dados relativamente homogêneos e concentrados em um intervalo específico. No entanto, a presença de valores extremos sugere a influência de fatores externos no experimento, como pequenas variações na execução dos lançamentos ou possíveis imprecisões na medição.

```{r}
library(leem)

ap01 <- read.csv2("ap01.csv")
str(ap01)

## Tratamento dos dados

dist <- ap01$dist
sort(dist)

## Tabela de Frequência

tab <- dist |>
  new_leem(variable = 2) |>
  tabfreq(k = 5)

tab
```


## Considerações finais

A prática pode ser considerada como bem sucedida.
Os principais objetivos foram cumpridos.
Os dados apresentam baixa variabilidade, pois a maior parte das observações está concentrada em um intervalo relativamente estreito.
No entanto, observa-se a presença de valores extremos (como 2.50 e 2.80), que aumentam a dispersão total do conjunto.
Os métodos e passos que foram seguidos serviram para uma boa dinâmica de aprendizado sobre como executar um experimento com objetivo de análise estatística. Visando nesse caso, a coleta, organização e apresentação de dados.

Sugestão para possíveis melhorias nos próximos procedimentos experimentais.
Pode-se para os próximos experimentos verificar uma melhor forma de fixar a catapulta, com intenção de minimizar variação entre os lançamentos.

